language: objective-c
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1
branches:
  only:
    - master
    - develop

script:
  - set -o pipefail 
  - xcodebuild -project Cashier.xcodeproj -scheme Cashier -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 6S Plus' build test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
